package signing

import (
	"errors"
	"testing"
	"time"
)

const secret = "whsec_0123456789abcdef"

func TestVerifyAcceptsItsOwnSignature(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1","type":"dispute.opened"}`)
	now := time.Unix(1_767_225_600, 0).UTC()

	if err := Verify(secret, body, Sign(secret, body, now), now, defaultTolerance); err != nil {
		t.Fatalf("Verify() = %v, want nil", err)
	}
}

// The signature covers the body, so any edit to it - including one that keeps
// the length identical - has to fail.
func TestVerifyRejectsATamperedBody(t *testing.T) {
	t.Parallel()

	original := []byte(`{"amount_minor":1000}`)
	tampered := []byte(`{"amount_minor":9000}`)
	now := time.Now()

	err := Verify(secret, tampered, Sign(secret, original, now), now, defaultTolerance)
	if !errors.Is(err, ErrMismatch) {
		t.Fatalf("Verify() = %v, want ErrMismatch", err)
	}
}

func TestVerifyRejectsAnotherMerchantsSecret(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1"}`)
	now := time.Now()

	err := Verify("whsec_someone_else", body, Sign(secret, body, now), now, defaultTolerance)
	if !errors.Is(err, ErrMismatch) {
		t.Fatalf("Verify() = %v, want ErrMismatch", err)
	}
}

// A captured request must not stay valid forever, in either direction: a
// far-future timestamp is as suspicious as an old one.
func TestVerifyRejectsReplayOutsideTolerance(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1"}`)
	signedAt := time.Now()

	for name, now := range map[string]time.Time{
		"too old":    signedAt.Add(10 * time.Minute),
		"too future": signedAt.Add(-10 * time.Minute),
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			err := Verify(secret, body, Sign(secret, body, signedAt), now, defaultTolerance)
			if !errors.Is(err, ErrStaleTimestamp) {
				t.Fatalf("Verify() = %v, want ErrStaleTimestamp", err)
			}
		})
	}
}

func TestParseHeaderRejectsGarbage(t *testing.T) {
	t.Parallel()

	for _, header := range []string{
		"",
		"v1=abcd",                      // no timestamp
		"t=1735689600",                 // no signature
		"t=notanumber,v1=abcd",         // unparseable timestamp
		"t=1735689600,v1=nothexatall!", // unparseable signature
	} {
		if _, err := ParseHeader(header); !errors.Is(err, ErrMalformedHeader) {
			t.Errorf("ParseHeader(%q) = %v, want ErrMalformedHeader", header, err)
		}
	}
}

// Pins the exact bytes that get hashed. If this fails, the Go and TypeScript
// halves of the contract have drifted apart.
func TestComputeIsStableAcrossImplementations(t *testing.T) {
	t.Parallel()

	body := []byte(`{"hello":"world"}`)
	ts := time.Unix(1_700_000_000, 0).UTC()

	got := Sign("secret", body, ts)
	// Generated by the TypeScript side:
	//   createHmac("sha256", "secret").update(`1700000000.{"hello":"world"}`).digest("hex")
	want := "t=1700000000,v1=" +
		"654f06c856baf080af3fa272934823257a542d35cf1f88099338f850a60601a4"
	if got != want {
		t.Fatalf("Sign() = %s\nwant   %s\n(regenerate with the TypeScript side before trusting this)", got, want)
	}
}

// Rotation is not an instant. The new key is published, senders pick it up over
// minutes or hours, and deliveries signed with the old one keep arriving the
// whole time. Accepting only one secret forces a cutover where every in-flight
// delivery is rejected - which is why keys that can only be rotated with an
// outage never get rotated.
func TestVerifyAnyAcceptsEitherSideOfARotation(t *testing.T) {
	t.Parallel()

	const (
		next    = "whsec_rotated_in"
		current = "whsec_rotating_out"
	)
	body := []byte(`{"id":"evt_1"}`)
	now := time.Now()
	secrets := []string{next, current}

	for name, secret := range map[string]string{
		"signed with the new key": next,
		"signed with the old key": current,
	} {
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			if err := VerifyAny(secrets, body, Sign(secret, body, now), now, defaultTolerance); err != nil {
				t.Errorf("VerifyAny() = %v, want nil", err)
			}
		})
	}
}

func TestVerifyAnyStillRejectsAStranger(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1"}`)
	now := time.Now()

	err := VerifyAny([]string{"whsec_a", "whsec_b"}, body, Sign("whsec_c", body, now), now, defaultTolerance)
	if !errors.Is(err, ErrMismatch) {
		t.Fatalf("VerifyAny() = %v, want ErrMismatch", err)
	}
}

func TestVerifyAnyWithNoSecretsRejects(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1"}`)
	now := time.Now()

	if err := VerifyAny(nil, body, Sign("whsec_a", body, now), now, defaultTolerance); !errors.Is(err, ErrMismatch) {
		t.Fatalf("VerifyAny() = %v, want ErrMismatch", err)
	}
}

// A stale timestamp fails the same way for every secret, so it is reported once
// rather than after hashing against each.
func TestVerifyAnyReportsAStaleTimestampWithoutTryingEverySecret(t *testing.T) {
	t.Parallel()

	body := []byte(`{"id":"evt_1"}`)
	signedAt := time.Now()

	err := VerifyAny([]string{"a", "b", "c"}, body, Sign("a", body, signedAt),
		signedAt.Add(time.Hour), defaultTolerance)
	if !errors.Is(err, ErrStaleTimestamp) {
		t.Fatalf("VerifyAny() = %v, want ErrStaleTimestamp", err)
	}
}
