package signing

import (
	"errors"
	"testing"
	"time"
)

const secret = "whsec_0123456789abcdef"

func TestVerifyAcceptsItsOwnSignature(t *testing.T) {
	body := []byte(`{"id":"evt_1","type":"dispute.opened"}`)
	now := time.Unix(1_767_225_600, 0).UTC()

	if err := Verify(secret, body, Sign(secret, body, now), now, DefaultTolerance); err != nil {
		t.Fatalf("Verify() = %v, want nil", err)
	}
}

// The signature covers the body, so any edit to it - including one that keeps
// the length identical - has to fail.
func TestVerifyRejectsATamperedBody(t *testing.T) {
	original := []byte(`{"amount_minor":1000}`)
	tampered := []byte(`{"amount_minor":9000}`)
	now := time.Now()

	err := Verify(secret, tampered, Sign(secret, original, now), now, DefaultTolerance)
	if !errors.Is(err, ErrMismatch) {
		t.Fatalf("Verify() = %v, want ErrMismatch", err)
	}
}

func TestVerifyRejectsAnotherMerchantsSecret(t *testing.T) {
	body := []byte(`{"id":"evt_1"}`)
	now := time.Now()

	err := Verify("whsec_someone_else", body, Sign(secret, body, now), now, DefaultTolerance)
	if !errors.Is(err, ErrMismatch) {
		t.Fatalf("Verify() = %v, want ErrMismatch", err)
	}
}

// A captured request must not stay valid forever, in either direction: a
// far-future timestamp is as suspicious as an old one.
func TestVerifyRejectsReplayOutsideTolerance(t *testing.T) {
	body := []byte(`{"id":"evt_1"}`)
	signedAt := time.Now()

	for name, now := range map[string]time.Time{
		"too old":    signedAt.Add(10 * time.Minute),
		"too future": signedAt.Add(-10 * time.Minute),
	} {
		t.Run(name, func(t *testing.T) {
			err := Verify(secret, body, Sign(secret, body, signedAt), now, DefaultTolerance)
			if !errors.Is(err, ErrStaleTimestamp) {
				t.Fatalf("Verify() = %v, want ErrStaleTimestamp", err)
			}
		})
	}
}

func TestParseHeaderRejectsGarbage(t *testing.T) {
	for _, header := range []string{
		"",
		"v1=abcd",                      // no timestamp
		"t=1735689600",                 // no signature
		"t=notanumber,v1=abcd",         // unparseable timestamp
		"t=1735689600,v1=nothexatall!", // unparseable signature
	} {
		if _, err := ParseHeader(header); !errors.Is(err, ErrMalformedHeader) {
			t.Errorf("ParseHeader(%q) = %v, want ErrMalformedHeader", header, err)
		}
	}
}

// Pins the exact bytes that get hashed. If this fails, the Go and TypeScript
// halves of the contract have drifted apart.
func TestComputeIsStableAcrossImplementations(t *testing.T) {
	body := []byte(`{"hello":"world"}`)
	ts := time.Unix(1_700_000_000, 0).UTC()

	got := Sign("secret", body, ts)
	// Generated by the TypeScript side:
	//   createHmac("sha256", "secret").update(`1700000000.{"hello":"world"}`).digest("hex")
	want := "t=1700000000,v1=" +
		"654f06c856baf080af3fa272934823257a542d35cf1f88099338f850a60601a4"
	if got != want {
		t.Fatalf("Sign() = %s\nwant   %s\n(regenerate with the TypeScript side before trusting this)", got, want)
	}
}
