#!/usr/bin/env bash
#
# Plans the stack against LocalStack.
#
# Not a deployment: ECS, ELB and ECR are not in the Community edition, so this
# can never be applied. What it does prove is stronger than `tofu validate` -
# every data source resolves and every argument passes the provider's own
# validation, which is where a wrong attribute name or an invalid enum shows up.
set -euo pipefail

cd "$(dirname "$0")"

if ! command -v tofu >/dev/null 2>&1 && [ ! -x "$HOME/.local/bin/tofu" ]; then
  echo "opentofu not found. Install it, or add ~/.local/bin to PATH." >&2
  exit 1
fi
TOFU=$(command -v tofu 2>/dev/null || echo "$HOME/.local/bin/tofu")

# Generated, never committed: LocalStack hands out new ids every time its
# volume is recreated, so a checked-in file is stale after the first reset.
VPC=$(docker exec dr-localstack awslocal ec2 describe-vpcs --query 'Vpcs[0].VpcId' --output text)
SUBNETS=$(docker exec dr-localstack awslocal ec2 describe-subnets --query 'Subnets[0:4].SubnetId' --output json | tr -d ' \n')

python3 - "$VPC" "$SUBNETS" > localstack.auto.tfvars <<'PY'
import json, sys
vpc, subnets = sys.argv[1], json.loads(sys.argv[2])
print(f'''# Generated by plan-against-localstack.sh. Do not commit.
region      = "us-east-1"
environment = "staging"
vpc_id             = "{vpc}"
private_subnet_ids = {json.dumps(subnets[0:2])}
public_subnet_ids  = {json.dumps(subnets[2:4])}
certificate_arn         = "arn:aws:acm:us-east-1:000000000000:certificate/11111111-2222-3333-4444-555555555555"
database_url_secret_arn = "arn:aws:secretsmanager:us-east-1:000000000000:secret:dispute-router/database-url-AbCdEf"
redis_url        = "redis://localhost:6379"
image_tag        = "a1b2c3d4"
dashboard_origin = "http://localhost:4200"
alarm_topic_arn  = ""''')
PY

[ -d .terraform ] || "$TOFU" init -backend=false -input=false >/dev/null

AWS_ENDPOINT_URL=http://localhost:4566 \
AWS_ACCESS_KEY_ID=test AWS_SECRET_ACCESS_KEY=test AWS_REGION=us-east-1 \
  "$TOFU" plan -input=false "$@"
